import { Item, ItemType, User, Review, Notification, PaymentMethod, Transaction } from './types';

const mockReviewsForAria: Review[] = [
    {
        id: 'review1',
        itemId: 'item5',
        rating: 5,
        comment: 'Aria\'s UI kit is incredible. The components are well-designed and the documentation is crystal clear. Saved me weeks of work!',
        reviewerId: 'user2',
        reviewerName: 'Aarush Gandhi',
        reviewerProfilePictureUrl: `https://images.unsplash.com/photo-1583864697784-a0efc8379f70?q=80&w=256&auto=format&fit=crop`,
        postedDate: '2023-10-24T10:00:00Z',
    },
];

const mockReviewsForKaelen: Review[] = [
    {
        id: 'review2',
        itemId: 'item2',
        rating: 5,
        comment: 'The quality of this generative art is insane. The high-resolution files were perfect for my project. A true artist!',
        reviewerId: 'user3',
        reviewerName: 'Jax Orin',
        reviewerProfilePictureUrl: `https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=256&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D`,
        postedDate: '2023-10-27T12:00:00Z',
    }
];

const mockReviewsForJax: Review[] = [
     {
        id: 'review3',
        itemId: 'item1',
        rating: 4,
        comment: 'The 3D model is well-optimized and looks great in-engine. A few textures needed minor adjustments, but overall a solid asset.',
        reviewerId: 'user1',
        reviewerName: 'Aria Vance',
        reviewerProfilePictureUrl: `https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D`,
        postedDate: '2023-10-26T11:00:00Z',
    }
];

export const NOTIFICATIONS: Notification[] = [
    {
        id: 'notif1',
        userId: 'user1',
        type: 'new_review',
        message: 'Aarush Gandhi left a 5-star review on your item "Holographic UI Kit for Figma".',
        relatedItemId: 'item5',
        relatedUserId: 'user2',
        isRead: false,
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    },
    {
        id: 'notif2',
        userId: 'user1',
        type: 'item_sold',
        message: 'Your item "VR Controller Asset Pack" has been sold!',
        relatedItemId: 'item6',
        isRead: false,
        timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(), // 22 hours ago
    },
     {
        id: 'notif3',
        userId: 'user1',
        type: 'item_saved',
        message: 'Jax Orin saved your item "Holographic UI Kit for Figma".',
        relatedItemId: 'item5',
        relatedUserId: 'user3',
        isRead: true,
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    },
    {
        id: 'notif4',
        userId: 'user2',
        type: 'new_review',
        message: 'Jax Orin left a 5-star review on your item "Neural Net Art Print".',
        relatedItemId: 'item2',
        relatedUserId: 'user3',
        isRead: true,
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    },
     {
        id: 'notif5',
        userId: 'user3',
        type: 'new_review',
        message: 'Aria Vance left a 4-star review on your item "Cyberpunk Alleyway 3D Model".',
        relatedItemId: 'item1',
        relatedUserId: 'user1',
        isRead: false,
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
    }
];

const PAYMENT_METHODS: { [userId: string]: PaymentMethod[] } = {
    user1: [
        { id: 'pm1', brand: 'visa', last4: '4242', expiryMonth: 12, expiryYear: 2025, isDefault: true },
        { id: 'pm2', brand: 'mastercard', last4: '5555', expiryMonth: 8, expiryYear: 2026, isDefault: false },
        { id: 'pm5', brand: 'google-pay', email: 'aria@campus.edu', isDefault: false },
    ],
    user2: [
        { id: 'pm3', brand: 'visa', last4: '1234', expiryMonth: 6, expiryYear: 2024, isDefault: true },
    ],
    user3: [
        { id: 'pm4', brand: 'mastercard', last4: '8765', expiryMonth: 11, expiryYear: 2027, isDefault: true },
    ],
};

const TRANSACTIONS: { [userId: string]: Transaction[] } = {
    user1: [
        { id: 'txn1', date: '2023-10-26T11:05:00Z', itemTitle: 'Cyberpunk Alleyway 3D Model', amount: 3500.00, currency: 'INR', status: 'completed', transactionType: 'purchase' },
        { id: 'txn2', date: '2023-10-20T09:30:00Z', itemTitle: 'AI Art Prompt Engineering Service', amount: 2000.00, currency: 'INR', status: 'completed', transactionType: 'purchase' },
    ],
    user2: [
        { id: 'txn3', date: '2023-10-27T12:05:00Z', itemTitle: 'Neural Net Art Print "Electric Dreams"', amount: 1800.00, currency: 'INR', status: 'completed', transactionType: 'purchase' },
    ],
    user3: [
         { id: 'txn4', date: '2023-10-24T10:05:00Z', itemTitle: 'Holographic UI Kit for Figma', amount: 4500.00, currency: 'INR', status: 'completed', transactionType: 'purchase' },
    ],
};

export const USERS: User[] = [
  {
    id: 'user1',
    name: 'Aria Vance',
    email: 'aria@campus.edu',
    password: 'password123',
    schoolLevel: 'College',
    grade: 'Junior',
    profilePictureUrl: `https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D`,
    reviewsReceived: mockReviewsForAria,
    savedItemIds: ['item2', 'item3'],
    purchasedItemIds: ['item1', 'item7'],
    bio: 'VR/AR developer and UI/UX enthusiast. Building the interfaces of tomorrow. Let\'s connect and create!',
    twitterUrl: 'https://twitter.com/ariavance',
    linkedinUrl: 'https://linkedin.com/in/ariavance',
    githubUrl: 'https://github.com/ariavance',
    notificationSettings: {
        inApp: { newMessages: true, itemSold: true, newReviews: true, priceDrops: true, itemSaved: true },
        email: { newMessages: true, itemSold: true, newReviews: false, priceDrops: false, itemSaved: false, weeklyDigest: true },
    },
    paymentMethods: PAYMENT_METHODS['user1'],
    transactionHistory: TRANSACTIONS['user1'],
    plan: 'Pro',
    martcoinBalance: 150,
    cart: [],
  },
  {
    id: 'user2',
    name: 'Aarush Gandhi',
    email: 'kaelen@campus.edu',
    password: 'password123',
    schoolLevel: 'College',
    grade: 'Senior',
    profilePictureUrl: `https://images.unsplash.com/photo-1583864697784-a0efc8379f70?q=80&w=256&auto=format&fit=crop`,
    reviewsReceived: mockReviewsForKaelen,
    savedItemIds: ['item1', 'item5'],
    purchasedItemIds: ['item2'],
    bio: 'AI artist exploring the intersection of neural networks and creativity. My algorithms dream in code.',
    twitterUrl: '',
    linkedinUrl: 'https://linkedin.com/in/kaelenrivas',
    githubUrl: 'https://github.com/kaelenrivas',
    notificationSettings: {
        inApp: { newMessages: true, itemSold: true, newReviews: true, priceDrops: true, itemSaved: false },
        email: { newMessages: false, itemSold: true, newReviews: false, priceDrops: false, itemSaved: false, weeklyDigest: true },
    },
    paymentMethods: PAYMENT_METHODS['user2'],
    transactionHistory: TRANSACTIONS['user2'],
    plan: 'Free',
    martcoinBalance: 80,
    cart: [],
  },
  {
    id: 'user3',
    name: 'Jax Orin',
    email: 'jax@campus.edu',
    password: 'password123',
    schoolLevel: 'College',
    grade: 'Sophomore',
    profilePictureUrl: `https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=256&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D`,
    reviewsReceived: mockReviewsForJax,
    savedItemIds: ['item4', 'item6'],
    purchasedItemIds: ['item5'],
    bio: '3D modeling and environment artist. Specializing in cyberpunk and sci-fi aesthetics for games and film.',
    twitterUrl: 'https://twitter.com/jaxorin',
    linkedinUrl: '',
    githubUrl: '',
    notificationSettings: {
        inApp: { newMessages: true, itemSold: true, newReviews: true, priceDrops: false, itemSaved: true },
        email: { newMessages: true, itemSold: true, newReviews: true, priceDrops: false, itemSaved: false, weeklyDigest: false },
    },
    paymentMethods: PAYMENT_METHODS['user3'],
    transactionHistory: TRANSACTIONS['user3'],
    plan: 'Free',
    martcoinBalance: 200,
    cart: [],
  },
];

export const ITEMS: Item[] = [
  {
    id: 'item1',
    title: 'Cyberpunk Alleyway 3D Model',
    description: 'A game-ready, detailed 3D environment model of a futuristic cyberpunk alley. Includes PBR textures, modular assets, and sample lighting setup for Blender.',
    price: 3500.00,
    isNegotiable: false,
    category: ['3D Models'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1576064125237-a8944359d97a?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Jax Orin',
    sellerId: 'user3',
    postedDate: '2023-10-26T10:00:00Z',
    status: 'available',
    condition: 'Used - Good',
  },
  {
    id: 'item2',
    title: 'Neural Net Art Print "Electric Dreams"',
    description: 'A high-resolution (300 DPI) generative art piece created with a custom StyleGAN model. Perfect for printing and framing as a unique piece of tech-inspired art.',
    price: 1800.00,
    isNegotiable: false,
    category: ['Digital Art'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1634017835447-353d4a822559?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aarush Gandhi',
    sellerId: 'user2',
    postedDate: '2023-10-25T14:30:00Z',
    status: 'available',
    condition: 'New',
  },
  {
    id: 'item3',
    title: 'Retrowave Music Pack - "Neon Drive"',
    description: 'A collection of 5 royalty-free synthwave tracks perfect for games, videos, or streams. Includes loops and full-length versions in WAV and MP3.',
    price: 2200.00,
    isNegotiable: true,
    category: ['Synthwave Tracks'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Jax Orin',
    sellerId: 'user3',
    postedDate: '2023-10-24T18:00:00Z',
    status: 'available',
    condition: 'Used - Like New',
  },
  {
    id: 'item4',
    title: 'Unity C# Scripting Session',
    description: 'One hour of personalized tutoring for Unity game development in C#. Covering topics from beginner scripting to advanced mechanics and optimization.',
    price: 2500.00,
    isNegotiable: false,
    category: ['Code Scripts'],
    type: ItemType.RENT,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aarush Gandhi',
    sellerId: 'user2',
    postedDate: '2023-10-23T09:15:00Z',
    status: 'available',
    condition: 'New',
  },
  {
    id: 'item5',
    title: 'Holographic UI Kit for Figma',
    description: 'A comprehensive UI kit for creating futuristic, holographic interfaces. Includes 100+ components, global styles, and example screens. Perfect for sci-fi games or app concepts.',
    price: 4500.00,
    isNegotiable: true,
    category: ['UI Kits'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1629072412329-a5de4a81d115?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aria Vance',
    sellerId: 'user1',
    postedDate: '2023-10-22T11:45:00Z',
    status: 'available',
    condition: 'New',
  },
  {
    id: 'item6',
    title: 'VR Controller Asset Pack',
    description: 'A set of 5 futuristic, low-poly VR controller models. Optimized for performance and ready to be integrated into your Unity or Unreal Engine project.',
    price: 1500.00,
    isNegotiable: true,
    category: ['VR/AR Assets', '3D Models'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1554835150-383791419747?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aria Vance',
    sellerId: 'user1',
    postedDate: '2023-10-21T16:20:00Z',
    status: 'available',
    condition: 'Used - Like New',
  },
    {
    id: 'item7',
    title: 'AI Art Prompt Engineering Service',
    description: 'Book a consultation session to craft the perfect prompts for your AI art generator (Midjourney, DALL-E, etc.). Get the exact style and result you\'re looking for.',
    price: 2000.00,
    isNegotiable: false,
    category: ['Digital Art'],
    type: ItemType.RENT,
    imageUrl: 'https://images.unsplash.com/photo-1641950289196-109033f7f2ba?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aarush Gandhi',
    sellerId: 'user2',
    postedDate: '2023-10-20T12:00:00Z',
    status: 'available',
    condition: 'New',
  },
  {
    id: 'item8',
    title: 'Animated "Glitch" Text Effects',
    description: 'A pack of 10 customizable glitch text effects for After Effects. Easily drag-and-drop to give your video titles a cool, cyberpunk feel.',
    price: 1200.00,
    isNegotiable: false,
    category: ['UI Kits'],
    type: ItemType.SALE,
    imageUrl: 'https://images.unsplash.com/photo-1502404679469-1a1358390ee8?q=80&w=800&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    seller: 'Aria Vance',
    sellerId: 'user1',
    postedDate: '2023-10-19T10:30:00Z',
    status: 'available',
    condition: 'Used - Good',
  },
];